{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "994f6781-361f-40b8-bfb6-ce75c5869451",
        "fromColumn": "Data de início",
        "fromTable": "Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0885bb58-c282-4840-b04b-38d2594cbe8e"
      },
      {
        "name": "bb50f3da-2791-4c60-aa12-f2ef837fd905",
        "fromColumn": "Data final",
        "fromTable": "Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ab301b0e-e698-4efa-a743-998f9bbcaa40"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_5e33b47e-a371-4056-b733-58fe34004cc0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "874eb366-37b5-4049-aeb2-a9a6f62ab794",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d6accda-02bf-4813-80ff-1628fb509c53",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1147d056-8242-47a1-93a4-cf33c8c640ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "531f81dc-1eb4-4873-8043-cabfb1f4c0cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0a0f6558-f326-4aaa-a113-32bea4ba19ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c5a30d87-78ee-4158-8693-2dad40ea9b90",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c145818b-9273-4b60-af1c-9e7dc1faad94",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4afac208-1a97-4aa7-a4f6-5ce77cdf90b9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a2dca115-c974-43cf-b8b5-d4572c0607e5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "eda5d1a6-1b89-49ae-81c0-391be43e4015",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "26bb721d-e3c0-4410-8215-aa680ece4585",
                "ordinal": 3
              }
            ],
            "lineageTag": "88aa96e2-f479-4334-a4d0-a4862c1f14b9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "ac9c8839-794b-4253-a46d-47a97bd3d671",
        "partitions": [
          {
            "name": "DateTableTemplate_5e33b47e-a371-4056-b733-58fe34004cc0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Projeto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c27c7660-8c77-4042-938a-ac3bd35fa353",
            "sourceColumn": "Projeto",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d33fc9f-7bcc-4f98-a08a-ce0821884c4f",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca46a2b0-6dbe-440a-92ba-48bca237fce7",
            "sourceColumn": "Tarefa",
            "summarizeBy": "none"
          },
          {
            "name": "Do utilizador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ecd2f5c-dc1d-4170-9c1c-4f8777758ec1",
            "sourceColumn": "Do utilizador",
            "summarizeBy": "none"
          },
          {
            "name": "Faturável",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e38943e-9629-4be3-87ee-2f826f8a6117",
            "sourceColumn": "Faturável",
            "summarizeBy": "none"
          },
          {
            "name": "Data de início",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "56ba4416-9cdc-4fd9-9c42-2e2699b5af22",
            "sourceColumn": "Data de início",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0885bb58-c282-4840-b04b-38d2594cbe8e"
                },
                "isDefault": true,
                "relationship": "994f6781-361f-40b8-bfb6-ce75c5869451"
              }
            ]
          },
          {
            "name": "Hora de início",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c9e703ad-737a-430c-9d08-815e64dbbaf4",
            "sourceColumn": "Hora de início",
            "summarizeBy": "none"
          },
          {
            "name": "Data final",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4c9a9509-e44a-4cd8-a6b3-63a83f2381a7",
            "sourceColumn": "Data final",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ab301b0e-e698-4efa-a743-998f9bbcaa40"
                },
                "isDefault": true,
                "relationship": "bb50f3da-2791-4c60-aa12-f2ef837fd905"
              }
            ]
          },
          {
            "name": "Fim do tempo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "8a504b68-6fb7-4b6e-a69d-58cfaf137b21",
            "sourceColumn": "Fim do tempo",
            "summarizeBy": "none"
          },
          {
            "name": "Duração (h)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c2dc01fa-1c7b-49f9-8029-cdc386dd1a69",
            "sourceColumn": "Duração (h)",
            "summarizeBy": "none"
          },
          {
            "name": "Duração (decimal)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3247826-bdcf-40f7-8dd4-9ecf7818c1f3",
            "sourceColumn": "Duração (decimal)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "348e55e2-818b-47c9-8aed-e31345635df0",
        "partitions": [
          {
            "name": "Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Repos\\ESTAT\\PowerBi\\PowerBiTest\\data\\Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Projeto\", type text}, {\"Cliente\", type text}, {\"Descrição\", type text}, {\"Tarefa\", type text}, {\"Do utilizador\", type text}, {\"Grupo\", type text}, {\"Email\", type text}, {\"Etiqueta\", type text}, {\"Faturável\", type text}, {\"Data de início\", type date}, {\"Hora de início\", type time}, {\"Data final\", type date}, {\"Fim do tempo\", type time}, {\"Duração (h)\", type time}, {\"Duração (decimal)\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Cliente\", \"Email\", \"Grupo\", \"Etiqueta\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0885bb58-c282-4840-b04b-38d2594cbe8e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8accef88-8022-44c0-8216-3d2ed931752d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "162d3adc-aaf7-4321-aebc-1a98f2edd145",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9a45f1d5-ade3-44f1-8196-adac341c31da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "96176e77-3976-47c0-ac84-64137bb5ed5f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "96828a51-e363-43b3-a333-ed675847d084",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cee7c93b-4efd-448e-91ab-3d32a2013043",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b221a637-443f-47f2-9365-8e2ff211a980",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fadd2b9a-6fa5-4516-b4e9-44855a29b613",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "19e6ed42-fb91-4b4e-a3d0-6c1e1dfaf84b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ea7fe834-6a81-4e19-bf0c-31642eb125fb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "15ac3d3b-fda7-4606-810d-31fad3a8a645",
                "ordinal": 3
              }
            ],
            "lineageTag": "ef7fcdf6-1653-4061-803a-3e650038b9f2"
          }
        ],
        "isHidden": true,
        "lineageTag": "038b3496-bb28-40e5-a0ab-689a8473e3bc",
        "partitions": [
          {
            "name": "LocalDateTable_0885bb58-c282-4840-b04b-38d2594cbe8e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024'[Data de início])), 1, 1), Date(Year(MAX('Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024'[Data de início])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ab301b0e-e698-4efa-a743-998f9bbcaa40",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "be4c7ca9-79d4-49f1-8c1f-e9e32d13a8f5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e147a4c5-4c67-44af-b8f8-5cb6558879d9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e3a0b349-d1f6-4706-a2ac-05a40aaafda8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a363dc0b-0074-42c7-a9e2-ae1fded79c5b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81a3e1ad-219b-4041-a958-be1077e57625",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4dc457f6-00df-41ed-ade0-fd7fd4042cdc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d81e9109-9994-4c65-a351-b483bcc86731",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "65a921e4-de66-407a-8546-e06b70cb9e3e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ae1be500-9275-40fa-8832-9301b891f137",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f08aaada-4844-470a-8af5-e9b9adf94f2c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "07bdd28e-b723-41f0-8e5b-113c24b1fdd8",
                "ordinal": 3
              }
            ],
            "lineageTag": "e770a900-17ea-4ab2-a9a2-d8f549d8937a"
          }
        ],
        "isHidden": true,
        "lineageTag": "4b7e1cda-1b0d-4ffd-88d5-b87cc05cfcc9",
        "partitions": [
          {
            "name": "LocalDateTable_ab301b0e-e698-4efa-a743-998f9bbcaa40",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024'[Data final])), 1, 1), Date(Year(MAX('Clockify_Relatório_De_Tempo_Detalhado_01_01_2024-31_12_2024'[Data final])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}